# Rolled out onto all machines
required_roles:
  - bash # Includes helper scripts and bash configuration
  - git # Only config
#  - nvim
#  - vscode
#  - docker

# For private PCs aka my private clients
private_dev_env:
  roles:
  - ssh
  #- wireguard-client <- Can't work on macos lol
  #- node
  #- yarn
  #- pnpm
  #- nvm
  #- rust # Uses rustup to setup rust
  #- discord

# For the server that I will SSH into
cloud_dev_env:
  roles:
  # - wireguard-server

# Role vars
git:
  name: 89Q12
  email: zofi@xamh.de
ssh:
# Example data, this should be added encrypted data
#  keys:
#  - key: "id_ed25519.pub"
#    value: "esdfds"