required_roles:
  - bash # Includes helper scripts and bash configuration
  - git # Only config
#  - emacs
#  - vim
#  - vscode
#  - fluxcli
#  - helm
#  - minio-cli
#  - docker

vars:
  git:
    name: 89Q12
    email: zofi@xamh.de
