required_roles:
  - zsh
  - emacs
  - starship
  - vim
  - vscode
  - ssh
  - kubectl # Includes Kctx
  - docker
  - firefox
  - fluxcli
  - helm
  - minio-cli
  - git # Only config

vars:
  git:
    name: 89Q12
    email: zofi@xamh.de
