---
- name: check if os is supported
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_os_family | lower }}.yml"
  register: st

- name: Fail when usupported OS
  ansible.builtin.fail:
    msg: "OS unsupported"
  when: not st.stat.exists
- name: Install Bash
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Existing install
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-bash"
  register: install

- name: Install OMYBASH
  ansible.builtin.command: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/ohmybash/master/tools/install.sh)" "" --unattended'
  when: not ansible_check_mode and not install.stat.exists

- name: Copy custom scripts
  copy:
    src: "{{ role_path }}/scripts"
    dest: ~/.config/bash/
  with_fileglob:
  - "{{ role_path }}/scripts/*"

- name: Copy .bashrc
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.bashrc"
    src: "./.bashrc.j2"
    force: true # DO NOT DO LOCAL CHANGES AAAHHHHH IM GONNA FUCK THEM UP! This is intentional

