---
- name: DotFiles Config
  hosts: localhost
  connection: local
  tasks:
    - name: Run requried roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ required_roles }}"
      tags:
        - always
    - name: Run work roles
      include_roles:
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      with_items: "{{ work_dev_env.roles }}"
      tags:
        - work

    - name: Run private ioles
      include_roles:
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      with_items: "{{ private_dev_env.roles }}"
      tags:
        - private
