---
- name: DotFiles Config
  hosts: localhost
  connection: local
  tasks:
    - name: Run requried roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ required_roles }}"
      when: required_roles is defined
      tags:
        - always

    - name: Run work roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ role_name }}"
        name: "{{ role_name }}"
        public: yes
      loop_control:
        loop_var: role_name
      with_items: "{{ work_dev_env.roles }}"
      tags:
        - work

    - name: Run private roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ role_name }}"
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      with_items: "{{ private_dev_env.roles }}"
      tags:
        - private

    - name: Run cloud dev-env setup roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ role_name }}"
        name: "{{ role_name }}"
      vars:
        roleVars: rolesVars["{{ role_name }}"]
      loop_control:
        loop_var: role_name
      with_items: "{{ cloud_dev_env.roles }}"
      tags:
        - cloud