---
- name: Dump all vars
  debug:
    msg:  |-
          {% for k in vars.keys()|
                      reject('match', '^_.*$')|
                      list|
                      sort %}
          {{ k }}: {{ lookup('vars', k) }}
          {% endfor %}
- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh.keys }}"
  when: ssh.keys is defined
