---
- name: Run OS specific discord installation
  ansible.builtin.import_tasks: "{{ ansible_os_family }}.yml"

- name: Setup Better discord
  ansible.builtin.import_tasks: "setup_better_discord.yml"
  when: {{ discord.betterDiscord.enabled }}
