---
- name: Clone better discord
  ansible.builtin.git:
    repo: 'https://github.com/BetterDiscord/BetterDiscord.git'
    dest: /opt/betterDiscord
    single_branch: yes
    version: main
    update: yes
    clone: yes

- name: Setup the project using yarn
  community.general.yarn:
    path: /opt/betterDiscord
  when: not ansible_check_mode

- name: Build better discord
  ansible.builtin.script:
    cmd: yarn --cwd /opt/betterDiscord/ run build
  when: not ansible_check_mode

- name: Inject better discord
  ansible.builtin.script:
    cmd: yarn --cwd /opt/betterDiscord/ run inject
  when: not ansible_check_mode
