---
- name: Clone better discord
  ansible.builtin.git:
    repo: 'https://github.com/BetterDiscord/BetterDiscord.git'
    dest: /opt/betterDiscord
    single_branch: yes
    version: main
    update: yes
    clone: yes
- name: Setup the project using yarn
  community.general.yarn:
    path: /opt/betterDiscord

- name: Build better discord
  ansible.builtin.script:
    cmd: yarn --cwd /opt/betterDiscord/ run build

- name: Build better discord
  ansible.builtin.script:
    cmd: yarn --cwd /opt/betterDiscord/ run inject
#- name: Install plugins
