---
- name: Check if package is defined
  ansible.builtin.fail: msg="package is not installed, can't install undefined"
  when: package is undefined

- name: Check if install tasks exist for {{ ansible_os_family }}
  ansible.builtin.stat:
    path: "install_tasks_{{ ansible_os_family }}.yml"
  register: os_support

- name: Check system support
  ansible.builtin.fail:
    msg: "OS unsupported"
  when: not os_support.stat.exists

- name: Installed required package(s)
  when: os_support.stat.exists
  ansible.builtin.include_tasks: "install_tasks_{{ ansible_os_family }}.yml"