---
- name: Install dependecies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - treesitter
    - fdfind
    - fzf
    - riggrep
    - luarocks
    - lazygit
- name: Install neovim package
  community.general.homebrew:
    name: neovim
    state: present
- name: Clone bootstrapping git repo
  ansible.builtin.git:
    clone: true
    repo: git@github.com:89Q12/nvim-conf.git
    dest: ~/.config/nvim
